#!/bin/sh

# deno
curl -fsSL https://deno.land/install.sh | sh -s -- -y

# bun
curl -fsSL https://bun.sh/install | bash

# node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm install 22

_DENO_BIN=$HOME/.deno/bin/debuno
_INSTALL_DIR=$HOME/.debuno

rm -rf $_INSTALL_DIR

if  [ "$0" = "sh" ]; then  
    echo "Installing debuno..."
    echo "INSTALL_DIR: $_INSTALL_DIR"
    echo

    git clone https://github.com/serebano/debuno.git $_INSTALL_DIR
else
    _INSTALL_DIR=$(dirname $(realpath $0))

    echo "Installing debuno in dev mode..."
    echo "INSTALL_DIR: $_INSTALL_DIR"
    echo
fi

_BIN_DIR=$_INSTALL_DIR/bin
_BIN=$_BIN_DIR/debuno

if [ -L $_DENO_BIN ]; 
    then rm $_DENO_BIN; fi

if ! [ -L $_DENO_BIN ]; 
    then ln -s $_BIN $_DENO_BIN; fi

exec debuno info