#!/bin/sh

_IS_DEV=false
_DENO_BIN=$HOME/.deno/bin/debuno

_BASE=$(dirname $(realpath $0))
_INSTALL_DIR=$HOME/.debuno

rm -rf $_INSTALL_DIR

if [ -d $_BASE/.git ]; then  
    _IS_DEV=true
    _INSTALL_DIR=$_BASE

    echo "Installing debuno in dev mode..."
    echo "INSTALL_DIR: $_INSTALL_DIR"
else
    echo "Installing debuno..."
    echo "INSTALL_DIR: $_INSTALL_DIR"
    git clone https://github.com/serebano/debuno.git $_INSTALL_DIR
fi

_BIN_DIR=$_INSTALL_DIR/bin
_BIN=$_BIN_DIR/debuno

if [ -L $_DENO_BIN ]; 
    then rm $_DENO_BIN; fi

if ! [ -L $_DENO_BIN ]; 
    then ln -s $_BIN $_DENO_BIN; fi

exec debuno check